apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: yeongbeen93/callme-service
      jib: {}
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
      timezone: "Local"